# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # vagrant-registration plugin settings
  config.registration.username = ENV['SUB_USERNAME']
  config.registration.password = ENV['SUB_PASSWORD']
  config.registration.unregister_on_halt = false

  config.vm.define "rhel7" do |rhel7|
    rhel7.vm.box = "generic/rhel7"
    rhel7.vm.hostname = "rhel7"
  end
  config.vm.define "rhel8" do |rhel8|
    rhel8.vm.box = "generic/rhel8"
    rhel8.vm.hostname = "rhel8"
  end
  config.vm.define "rhel9" do |rhel9|
    rhel9.vm.box = "generic/rhel9"
    rhel9.vm.hostname = "rhel9"
  end

end
